version: "3.7"

networks:
  sourcify:

services:
  ui:
    restart: always
    networks:
      - sourcify
    image: ethereum/sourcify/ui
    container_name: ethereum/sourcify/ui
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "${UI_EXTERNAL_PORT}:80"
